# Generated by Django 4.0.4 on 2022-05-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='', upload_to='blogImg/')),
                ('category', models.CharField(blank=True, choices=[(None, 'Choose...'), ('Technology', 'Technology'), ('Software', 'Software'), ('Business', 'Business'), ('Fashion', 'Fashion'), ('Lifestyle', 'Lifestyle'), ('Travel', 'Travel'), ('Food', 'Food')], max_length=200)),
                ('status', models.CharField(choices=[('', '')], max_length=200)),
            ],
        ),
    ]
