# Generated by Django 4.0.4 on 2022-06-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_user_comment_user_blogview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(default='default.jpg'),
        ),
    ]
